services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      DOCKER_API_VERSION: "1.40"
    command:
      - --label-enable
      - --cleanup
      - --schedule
      - "0 0 4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
